package model.polo;
// Generated Jun 16, 2017 3:01:29 PM by Hibernate Tools 4.3.1



/**
 * Foods generated by hbm2java
 */
public class Foods  implements java.io.Serializable {


     private Integer idfood;
     private String foodName;
     private String info;
     private String note;
     private Integer price;
     private String image;

    public Foods() {
    }

	
    public Foods(String foodName) {
        this.foodName = foodName;
    }
    public Foods(String foodName, String info, String note, Integer price, String image) {
       this.foodName = foodName;
       this.info = info;
       this.note = note;
       this.price = price;
       this.image = image;
    }
   
    public Integer getIdfood() {
        return this.idfood;
    }
    
    public void setIdfood(Integer idfood) {
        this.idfood = idfood;
    }
    public String getFoodName() {
        return this.foodName;
    }
    
    public void setFoodName(String foodName) {
        this.foodName = foodName;
    }
    public String getInfo() {
        return this.info;
    }
    
    public void setInfo(String info) {
        this.info = info;
    }
    public String getNote() {
        return this.note;
    }
    
    public void setNote(String note) {
        this.note = note;
    }
    public Integer getPrice() {
        return this.price;
    }
    
    public void setPrice(Integer price) {
        this.price = price;
    }
    public String getImage() {
        return this.image;
    }
    
    public void setImage(String image) {
        this.image = image;
    }




}


