package model.polo;
// Generated Jun 16, 2017 3:01:29 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Menus generated by hbm2java
 */
public class Menus  implements java.io.Serializable {


     private Integer idmenu;
     private String idfood;
     private String info;
     private Date menuDate;

    public Menus() {
    }

	
    public Menus(String idfood) {
        this.idfood = idfood;
    }
    public Menus(String idfood, String info, Date menuDate) {
       this.idfood = idfood;
       this.info = info;
       this.menuDate = menuDate;
    }
   
    public Integer getIdmenu() {
        return this.idmenu;
    }
    
    public void setIdmenu(Integer idmenu) {
        this.idmenu = idmenu;
    }
    public String getIdfood() {
        return this.idfood;
    }
    
    public void setIdfood(String idfood) {
        this.idfood = idfood;
    }
    public String getInfo() {
        return this.info;
    }
    
    public void setInfo(String info) {
        this.info = info;
    }
    public Date getMenuDate() {
        return this.menuDate;
    }
    
    public void setMenuDate(Date menuDate) {
        this.menuDate = menuDate;
    }




}


